### ISSUE TITLE
question about eeprom

### ISSUE THREAD

**Issue by kakaducsy** [G6EJD/Using-ESP8266-EEPROM#1]
Hi,
I see you use command : EEPROM.get and EEPROM.put
but I checked lib EEPROM.cpp of esp8266 : https://github.com/esp8266/Arduino/blob/master/libraries/EEPROM/EEPROM.cpp
I dont see EEPROM.get and EEPROM.put
but It work ?????
why ??

**Comment by G6EJD** [comment]
A reminder that .get and .put are Arduino primitives see here https://www.arduino.cc/en/Reference/EEPROMGet
So it’s right that the compiler supports those function albeit implemented by a series of eeprom.read and eeprom.write ESP8266 primitives. In effect they (get and put) are macros that get expanded into suitable code to implement but we never see it unless we inspect the compiler output in op-codes.
It’s all standard code.
